// import { Inter } from "next/font/google";
// import { AuthContextProvider } from "@/context/AuthContext";
import { AuthContextProvider } from "../context/AuthContext";
import "./globals.css";
import { Roboto } from "next/font/google";
import { Lora } from "next/font/google";
import { Roboto_Mono } from "next/font/google";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  weight: ["100", "300", "400", "500", "700"],
});
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["100", "300", "400", "500", "700", "900"],
});
const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  weight: ["400", "500", "700"],
});
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Game Dev Diaries",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className + ""}>
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
